language: python
os: linux
dist: trusty
group: edge
sudo: required
python: '3.6'
git:
  depth: 3
branches:
  only:
  - master

env:
  global:
  - BUILD_VERSION="6.0.0"
  - secure: Uw8jWg5zQDigVUTrWkhWe0gxKBugxWQi7MLJjPIrg9YZsDXbLouJQAxvGVR0Rcr8RjXjk383Ob+jiMWp7WbSXT7HaNCc3DCqno2CxlzpN1WgRo9OAvdhWIOUTRuuLrI0B5TMCkhCu7WfpCyXY/UtwBWBddugF9xz8gQK/SBtgIyuJxRb4EH4iBl+c6igGUxKQ8KVaN/C+7PPONCA3TWHx65qyn+QcblAfTn0EcEKf7Stm+3eTZSwG2G0rctuoywAKGjQTlpihnKBh0R02kH15YU9byHc44EiNJwS99UVkc8pzPCGr+fiM+4m7H2IEc3b2N7Fcao0v99psXzi88bXXYf581lCVED+zVxFc1cI3gRt2p0ds6DR5FPMi3ZeoQLKanhqOg/rcPV0EPokoI+Sq2DLDtbgnNDxlGDfB0Q5vm+ILX36btsTq4/mKMBnauPmi1ePtHHxUiReYzNK4qRAQ8TpZMpicsHgOo2KAfZkHbJUVDtgn8eiMQnYn+6NHj0VAYB1Ef/8hCs1Yj8eXPLp+KF9NMY11JgmAJxi+ZcglWBS9rg4+mC+rHQGl6eDQTr5htPRdKteQ0k2eFmynmJW4C0ogNZf3ZJSKDWq5UnfhDjTwA9RrOEC2JKC9x0uM7BZqypj4ZaVGNoF5zCY3zyKytJUG0/A8sXH95rKqBZbVo8=

before_install:
- sudo add-apt-repository ppa:mc3man/testing6 -y
- sudo apt-get -qq update
# - sudo apt-get install -y python3-dev python3-setuptools libarchive13
#   wget desktop-file-utils aria2 fuse gnupg2 build-essential file libglib2.0-bin

install:
- wget https://github.com/ozmartian/vidcutter/archive/${BUILD_VERSION}.tar.gz -O ./vidcutter.tar.gz
- tar -xvf ./vidcutter.tar.gz
- mv vidcutter-${BUILD_VERSION}/* .
- rm -rf vidcutter.tar.gz vidcutter-${BUILD_VERSION}
- python3 setup.py build_ext -i

script:
- cd _packaging/appimage
- "./build.sh"
- mv ./out/VidCutter--x86_64.AppImage "${TRAVIS_BUILD_DIR}/VidCutter-${BUILD_VERSION}-x64.AppImage"
- echo "Done!"

notifications:
  email: false

before_deploy:
- git config --local user.name "Pete Alexandrou"
- git config --local user.email "pete@ozmartians.com"
- git fetch -t
- git tag -d ${BUILD_VERSION}
- git remote set-url origin https://ozmartian:${GITHUB_TOKEN}@github.com/ozmartian/vidcutter-appimage.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -am v${BUILD_VERSION} ${BUILD_VERSION}

deploy:
  provider: releases
  api_key:
    secure: aa1y8Qks56bt7YGJupHEufrgTJcc4YmS23UXbVTTqLy8ZMNUe4JL6o5PJGZt07lFg2C1GriaWLscOwubHBmUNQHYFmFenIi+XYB2bHfx+IT4pmCrzRenZacW50DNtMtdGUT4ZAm6HKNKs5VmLF2sQP1Gnb0cokJHeyuym/xa3OA7IfQMjLRiMaR3Kfj95Hdxv6UUPDRL18CVrCe7GSgRo0PJerPQEATVwQxvz6QXxW/y9mujW9D7wzBMN4CiFzZjDDRFC0xq55IPb3Bg54mqKVUvNBxxf4Uu8NnWYxThFPy5LRbFT2Cnjqb7wtr9hzgfU8Y110xUQLJC/Xf6xwRsoVxC9LH41MRvLkucdbprYR+rqwwSO5bCxn6RoUCrXNKwfFBkwjhvt1+cC/GSsOkkMumfIeWuuOHNXV4A7uSatvVTYe3RkwmPPaj17aJ0lizBLC2p+1IQQp3jCInGRHjnrxsTGjuUrWGk9KKqrtqBQw8/yZ5sl3nlYQq33ELrAbb8QtnGUymxhIlzhd5FZ/JGyT88UEP+0NfwsTzl11PX1BdVDRdSSh8QW7TwSejctv8XNVVcb5aTyAw/IA36GnhuJuKVBOlwg6i9rW6oIRXgnGKMJsqP2PMWkNRfZlRToDgoYnoziYhunIQmfm+/fzTHhT/vIyDFemtF6GN64IlsgRM=
  file: "${TRAVIS_BUILD_DIR}/VidCutter-${BUILD_VERSION}-x64.AppImage"
  overwrite: true
  skip_cleanup: true
  on:
    repo: ozmartian/vidcutter-appimage
